name: GitHub Actions Ubuntu 22 Check

on:
  workflow_dispatch:

jobs:
  basic-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Print runner info
        run: |
          echo "GitHub Actions is working on ubuntu-22.04"
          uname -a